# Problem Statement : Hospital Patient Data Analysis

In [ ]:
import numpy as np
import pandas as pd

**1.Load the patient dataset and show summary with info()**

In [ ]:
df=pd.read_csv('Patient_Data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

 **2. Select only the columns relevant for billing**

In [ ]:
billing_columns = df[['PatientID', 'Department', 'Doctor', 'BillAmount']]
print("\nBilling Related Columns:")
print(billing_columns.head())

Billing Related Columns:
   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN


**3. Drop administrative columns**

In [ ]:
df = df.drop(columns=['ReceptionistID', 'CheckInTime'])

 **4. Use groupby to find total bill amount per department**

In [ ]:
department_bill = df.groupby('Department')['BillAmount'].sum()
print("\nTotal Bill Amount Per Department:")
print(department_bill)

Total Bill Amount Per Department:
Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

**5. Remove duplicate patient records based on PatientID**

In [ ]:
df = df.drop_duplicates(subset='PatientID')

In [ ]:
df.duplicated().sum()

np.int64(0)

**6. Fill missing BillAmount values with the mean bill amoun**t

In [ ]:
mean_bill = df['BillAmount'].mean()
df['BillAmount'] = df['BillAmount'].fillna(mean_bill)

In [ ]:
df.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    0
dtype: int64

**7. Merge the billing dataset with patient dataset on PatientID**

In [ ]:
billing_df = pd.read_csv("Billing_Data.csv")
merged_df = pd.merge(df, billing_df, on='PatientID', how='inner')

In [ ]:
print("\nMerged Dataset:")
print(merged_df.head())

Merged Dataset:
   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000              2000
1        102      Bob    Neurology   Dr. John  6233.333333              1500
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000              2500
3        104    David   Cardiology  Dr. Smith  6200.000000              3000
4        105      Eva  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount
0         3000
1         3500
2         5000
3         3200
4         4000

**8. Concatenate an additional DataFrame containing new patients (row-wise)**

In [ ]:
new_patients_df = pd.DataFrame({
    'PatientID': [201, 202],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Kumar', 'Dr. Rao'],
    'BillAmount': [4500, 6000]
})

combined_df = pd.concat([merged_df, new_patients_df], axis=0, ignore_index=True)

print("After Adding New Patients:")
print(combined_df)

After Adding New Patients:
   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000            2000.0
1        102      Bob    Neurology   Dr. John  6233.333333            1500.0
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000            2500.0
3        104    David   Cardiology  Dr. Smith  6200.000000            3000.0
4        105      Eva  Dermatology   Dr. Rose  6233.333333            1000.0
5        201      NaN   Cardiology  Dr. Kumar  4500.000000               NaN
6        202      NaN    Neurology    Dr. Rao  6000.000000               NaN

   FinalAmount
0       3000.0
1       3500.0
2       5000.0
3       3200.0
4       4000.0
5          NaN
6          NaN

**9. Concatenate new billing category columns like # ['InsuranceCovered', 'FinalAmount'] (column-wise)**

In [ ]:
billing_categories_df = pd.DataFrame({
    'InsuranceCovered': [1000] * len(combined_df),
    'FinalAmount': [4000] * len(combined_df)
})

final_dataset = pd.concat([combined_df, billing_categories_df], axis=1)

print("Final Dataset:")
print(final_dataset)

Final Dataset:
   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000            2000.0
1        102      Bob    Neurology   Dr. John  6233.333333            1500.0
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000            2500.0
3        104    David   Cardiology  Dr. Smith  6200.000000            3000.0
4        105      Eva  Dermatology   Dr. Rose  6233.333333            1000.0
5        201      NaN   Cardiology  Dr. Kumar  4500.000000               NaN
6        202      NaN    Neurology    Dr. Rao  6000.000000               NaN

   FinalAmount  InsuranceCovered  FinalAmount
0       3000.0              1000         4000
1       3500.0              1000         4000
2       5000.0              1000         4000
3       3200.0              1000         4000
4       4000.0              1000         4000
5          NaN              1000         4000
6          NaN              1000         4000

In [ ]:
df.head()

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333